const express = require('express');
const router = express.Router();
const loginRouter = require('./login');
const homeRouter = require('./home');
const orderRouter = require('./order');
const orderConfirmRouter = require('./order-confirm');
const orderCancelRouter = require('./order-cancel');
router.use('/',homeRouter);
router.use('/login',loginRouter);
router.use('/order',orderRouter);
router.use('/order-confirm',orderConfirmRouter);
router.use('/order-cancel',orderCancelRouter);
module.exports = router;